# remote_theme: pages-themes/modernist@v0.2.0
# plugins:
#   - jekyll-remote-theme
# title: Mussk17
# description: My main GitHub Pages site


remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme 
title: Mussk17
description: My main GitHub Pages site

